[project]
name = "simple-social-media-for-cat-content"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "FAIZAN KHAN", email = "202166657+faizanuddinkhan7@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
simple-social-media-for-cat-content = "simple_social_media_for_cat_content:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
